version: "3.8"

services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=appdb
      - MYSQL_PASSWORD=pass123
      - MYSQL_ROOT_PASSWORD=pass123
    networks:
      - sameNetworkAsMysql
    ports:
      - 3307:3306
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - sameNetworkAsMysql
    depends_on:
      - db

  frontend:
    restart: on-failure
    build:
      context: ./frontend
    ports:
      - 3001:3000
    networks:
      - sameNetworkAsMysql
    depends_on:
      - api

networks:
  sameNetworkAsMysql:
    driver: bridge
